import type { Metadata } from "next";
// Completely remove the problematic Geist imports
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Simplified approach - don't use next/font at all temporarily
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <div className="container mx-auto px-12">{children}</div>
      </body>
    </html>
  );
}
